version: '3.7'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ../pub:/var/www/html
  php:
    image: php:7-fpm
    volumes:
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
      - ../pub:/var/www/html